---
# tasks file for install-bcc package dependencies on ubuntu

- name: Install ubuntu 24.04 apt packages to build BCC tools
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - zip
      - bison
      - build-essential
      - cmake
      - flex
      - git
      - libedit-dev
      - libllvm18
      - llvm-18-dev
      - libcap2-bin
      - libclang-18-dev
      - python3
      - python3-pip
      - zlib1g-dev
      - libelf-dev
      - libfl-dev
      - python3-setuptools
      - liblzma-dev
      - libdebuginfod-dev
      - arping
      - netperf
      - iperf
      - libpolly-18-dev
      - "linux-headers-{{ ansible_kernel }}"
    state: present
  when: ansible_distribution_major_version == "24"

- name: Install ubuntu 22.04 apt packages to build BCC tools
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - zip
      - bison
      - build-essential
      - cmake
      - flex
      - git
      - libedit-dev
      - libllvm14
      - llvm-14-dev
      - libcap2-bin
      - libclang-14-dev
      - python3
      - python3-pip
      - zlib1g-dev
      - libelf-dev
      - libfl-dev
      - python3-setuptools
      - liblzma-dev
      - libdebuginfod-dev
      - arping
      - netperf
      - iperf
      - "linux-headers-{{ ansible_kernel }}"
    state: present
  when: ansible_distribution_major_version == "22"

- name: Set BCC cmake arguments
  ansible.builtin.set_fact:
    bcc_cmake_args: "-DPYTHON_CMD=python3"
