---
# tasks file for clone-kernel


# - ansible.builtin.debug:
#     msg: "{{ ansible_facts }}"

- name: Gather apt package facts
  ansible.builtin.package_facts:
    manager: apt
  when: ansible_facts['pkg_mgr'] == "apt"

- name: Install apt packages to build linux kernel
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg: "{{ linux_kernel_apt_pkgs }}"
    state: present
  when:
    - ansible_facts['pkg_mgr'] == "apt"
    - linux_kernel_apt_pkgs is not ansible.builtin.subset(ansible_facts.packages.keys() | list)

- name: Linux kernel downloaded
  stat:
    path: "{{ linux_source_dir }}"
  register: linux_exists

- name: Download Linux repo
  retries: 3
  delay: 3
  ansible.builtin.unarchive:
    creates: "{{ linux_source_dir }}"
    src: "https://git.kernel.org/torvalds/t/linux-{{ version }}.tar.gz"
    dest: /tmp
    remote_src: true
  register: linux_downloaded
  when: not linux_exists.stat.exists

- name: Ensure benchmark directory exists
  ansible.builtin.file:
    path: "{{ benchmark_dir }}"
    state: directory
    mode: '0755'
  when: linux_downloaded.changed

- name: Rename Linux repo
  ansible.builtin.command: mv "/tmp/linux-{{ version }}" "{{ linux_source_dir }}"
  when: linux_downloaded.changed

- name: Create kernel build directory
  ansible.builtin.file:
    path: "{{ linux_build_dir }}"
    state: directory
    mode: '0755'

- name: Generate kernel build config
  community.general.make:
    chdir: "{{ linux_source_dir }}"
    target: defconfig
    params:
      O: "{{ linux_build_dir }}"
