---
# tasks file for clone-kernel


# - ansible.builtin.debug:
#     msg: "{{ ansible_facts }}"

- name: Gather apt package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Install apt packages to build linux kernel
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg: "{{ linux_kernel_apt_pkgs }}"
    state: present
  when: linux_kernel_apt_pkgs is not ansible.builtin.subset(ansible_facts.packages.keys() | list)

- name: Download Linux repo
  ansible.builtin.unarchive:
    creates: "{{ linux_source_dir }}"
    src: "https://git.kernel.org/torvalds/t/linux-{{ version }}.tar.gz"
    dest: /tmp
    remote_src: true
    owner: "{{ ansible_facts['env']['USER'] }}"
  register: linux_downloaded

- name: Rename Linux repo
  become: true
  ansible.builtin.command: mv "/tmp/linux-{{ version }}" "{{ linux_source_dir }}"
  when: linux_downloaded.changed

- name: Create kernel directory
  become: true
  ansible.builtin.file:
    path: "{{ linux_source_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_facts['env']['USER'] }}"
  when: linux_downloaded.changed

- name: Create kernel build directory
  ansible.builtin.file:
    path: "{{ user_benchmark_dir }}/kernel-build"
    state: directory
    mode: '0755'

- name: Generate kernel build config
  community.general.make:
    chdir: "{{ linux_source_dir }}"
    target: defconfig
    params:
      O: "{{ user_benchmark_dir }}/kernel-build"
