---
benchmark_config:
  generic:
    benchmark: redis
    cpus: 0
    skip_clear_page_cache: false
    transparent_hugepages: never
    overcommit_memory: never_check
  redis:
    field_count: 512
    field_length: 512
    operation_count: 1000
    record_count: 4096
    read_proportion: 0.20
    update_proportion: 0.10
    insert_proportion: 0.10
    rmw_proportion: 0.10
    scan_proportion: 0.10
    delete_proportion: 0.30
    request_distribution: "uniform"
    mem_cgroup_size: "600M"
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - None
