---
benchmark_config:
  generic:
    benchmark: redis
    cpus: 0
    skip_clear_page_cache: false
    transparent_hugepages: never
    overcommit_memory: never_check
  redis:
    repeat: 1
    field_count: 1
    min_field_length: 4096
    field_length: 2097152
    outer_repeat: 20
    thread_count: 16
    record_count: 4096
    operation_count: 4096
    read_proportion: 0.05
    update_proportion: 0.00
    insert_proportion: 0.00
    rmw_proportion: 0.00
    scan_proportion: 0.00
    delete_proportion: 0.95
    field_length_distribution: "uniform"
    explicit_purge: true
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - mm_rss_stat
      - process_trace
      - madvise
      - perf
      - unmap_range
