---
benchmark_config:
  generic:
    benchmark: gap
    cpus: 0
    skip_clear_page_cache: false
    transparent_hugepages: always
    overcommit_memory: never_check
  gap:
    trials: 25
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - mm_rss_stat
      - process_trace
      - memory_usage
      - quanta_runtime
      - perf
      - zswap_runtime
