---
# tasks file for install-kernel


- name: Install apt package to launch new linux kernel
  become: true
  ansible.builtin.apt:
    pkg:
      - kexec-tools
    update_cache: true
    state: present


- name: Copy custom kernel over
  become: true
  ansible.builtin.copy:
    src: kernel/bzImage
    dest: /boot/custom-bzImage


- name: Set new kernel
  become: true
  ansible.builtin.command: kexec -l /boot/custom-bzImage --reuse-cmdline --initrd /boot/initrd.img

# - name: Install kernel headers
#   become: true
#   ansible.posix.synchronize:
#     src: kernel/include/
#     dest: /usr/include/


- name: Boot into new kernel
  become: true
  ansible.builtin.command: systemctl kexec
  ignore_errors: true
  async: 1
  poll: 1


- name: Wait for system to become reachable again
  wait_for_connection:
    delay: 5
    timeout: 600


- name: Get kernel version
  command: uname -a
  register: uname_result


- name: Print kernel version
  ansible.builtin.debug:
    var: uname_result.stdout_lines


# TODO(Patrick): Add symbolic links for these args
# - name: Install kernel modules
#   become: true
#   ansible.posix.synchronize:
#     src: kernel/lib/modules/
#     dest: /lib/modules/
#     checksum: true
#   register: modules
# - name: Display modules result
#   debug:
#       var: modules.stdout_lines
