---

- hosts: benchmark-kernel-build
  roles:
    - install-bcc
    # - clone-kernel
    # - install-kernel
    # - run-data-collection
    # - build-kernel

- hosts: test
  roles:
    - clone-kernel
