name: Build

on:
  push:
    branches:
      - main
    pull_request:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Cache Dependencies 📂
        uses: actions/cache@v3
        with:
          path: ~/.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Install Dependencies 📦
        run: python -m venv ./.venv && . ./.venv/bin/activate && pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - name: Run Ruff Linter 🚨
        run: . ./.venv/bin/activate && make lint
